In [1]:
import os
os.getcwd()
os.chdir('..')

In [9]:
# Specify libraries
import pandas as pd
import numpy as np

In [3]:
# Read in raw data
train_data = pd.read_csv('data/data_processed.csv')
test_data = pd.read_csv('data/data_test_processed.csv')

# Check rows and columns
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,12,2008,WD,Normal,250000

In [5]:
from scripts.one_hot_encoder import onehotencode_data

# Specify dependent variable and independent variables
train_Y = train_data.SalePrice
train_X = train_data.drop(columns = ['Id', 'SalePrice'])
test_X = test_data.drop(columns = ['Id'])

train_X = onehotencode_data(train_X)
test_X = onehotencode_data(test_X)

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [41]:
# Model number 1
X = train_X
y = train_Y

from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn import metrics

# training the model on training set
lin_reg = LinearRegression()

# Perform k-fold cross-validation
kf = KFold(n_splits=5, shuffle=True)
mse_scores = cross_val_score(lin_reg, X, y, scoring='neg_mean_squared_error', cv=kf)
r2_scores = cross_val_score(lin_reg, X, y, scoring='r2', cv=kf)

# Convert negative MSE scores to positive
mse_scores = -mse_scores

# Print cross-validation results
print(f"Cross-Validated Mean Squared Error: {np.mean(mse_scores)} Â± {np.std(mse_scores)}")
print(f"Cross-Validated R-squared: {np.mean(r2_scores)} Â± {np.std(r2_scores)}")

Cross-Validated Mean Squared Error: 1.5065792777577376e+16 Â± 3.013158345500607e+16
Cross-Validated R-squared: 0.7920109998708782 Â± 0.10964086371907159

array([1.18937970e+09, 7.53289597e+16, 6.66429187e+08, 9.53812706e+08,
       1.39067577e+09])

array([133808.99530024,  76012.20107105, 105045.27986847, 135390.77018703,
       615412.46831708, 175069.32901742, 169670.53887012, 176078.0146685 ,
       146547.81821547,  95882.89404589, 162984.93190835, 103168.72681434,
       177930.02547342, 261528.08082598, 178582.34504912,  90008.43013503,
       245904.73762563, 252090.35819023, 160755.22972885, 104898.0809143 ,
       184824.94730239, 143158.15338204,  97523.23014423, 127829.17130857,
        73675.06214783,  97230.27947283, 117812.76367697, 116347.91305841,
       136744.25176363, 170312.32006941, 162877.01037981, 359090.55836076,
       166926.25677113, 111684.09246371, 205093.86828537, 186133.71098585,
       106097.86091815, 180209.10191207, 128482.66511615, 191099.45619299,
       322551.58357981, 114413.64308545, 134902.83931377, 154242.25605857,
       143598.63934192,  48077.29020936, 144659.51889089, 137226.18879264,
       208730.1595305 , 122207.8804285 , 177297.85727785, 296067.99969532,
       105750.91571374, 122654.34571124, 149147.67355088,  98278.44775029,
       111052.91085334, 353136.94582851, 121745.42905937, 213252.18760951,
       155649.28242092, 110444.58626566, 162961.66624752, 268212.41881826,
       136112.23105041, 206865.03136941,  85107.4453952 , 162286.31951994,
       210060.28609271, 166249.69193908, 206861.09978081, 180391.68968138,
       333835.8418944 , 312471.06751756, 113123.66815493, 217758.85945314,
       210854.21707287, 138448.99098989, 109640.56790989, 166305.52539023,
       229091.87024506, 367745.60857192, 155332.98673064, 160268.05729413,
       152376.73390615, 290028.5686993 , 355001.80899901, 127592.64603618,
       183934.41301619, 122056.39425675, 142475.35339243, 148452.94069266,
        85637.63398852, 192054.76825862, 115891.55819854, 215087.32041036,
       312877.99670323, 219909.67244662, 191559.59726463, 129049.49521903,
       183935.01981696, 141568.82103873, 100059.78684861, 195592.24562764,
        95295.7683695 ,  76791.85368842, 200725.24259579, 235100.0889571 ,
       216167.9336208 , 166069.66215133, 343750.15094846, 137087.89540526,
       233825.11860167, 222509.08548651, 195747.77136032, 256899.71362947,
       417867.86078635, 177890.34988514, 231801.08109044, 136339.83868517,
        62099.3512735 , 224809.75885646, 111358.92047262, 109389.16738494,
       241415.05595274, 116495.80499655, 169647.817272  , 153424.40376049,
       148327.19159574, 285881.27070159, 154271.21386535, 215497.58051424,
       125768.52126942, 129728.10796036, 304787.63185198, 214301.84907827,
       411947.25173822, 174797.90117838, 202686.19813554, 116076.98793855,
       394342.57167511, 112213.94455193, 222068.28072339, 137057.89066791,
       200716.05142891, 278096.62361464, 185023.53060834, 241035.23772412,
        66301.32785269, 246713.69530822, 343873.46480621, 371342.71562153,
       172486.50696299, 222043.77323378,  91359.08482397, 184004.16663874,
       193533.45588477, 234427.28259193, 291301.37240577, 139947.85476779,
       179923.54453893, 163187.89399455, 216485.86360142, 282102.00647728,
       165093.82891693, 119777.15171875, 188616.49973251, 209582.77063648,
       129051.1754066 , 101460.62787021, 225028.93781131, 288901.02420721,
       209068.01721021, 135014.02080676, 128247.44529691, 164308.90696715,
       224464.77745629, 108917.36537851, 254747.56113372, 147689.4535865 ,
       145694.06145183, 248800.04221681,  75458.90729421, 159324.95803752,
       146781.77451693, 140765.81470225, 151798.49879846, 132843.7029686 ,
       132125.9464021 , 126609.01721741, 288682.99375159, 184693.41866884,
       165406.58751506, 128838.96466505, 121180.77555642, 184862.62761164,
        98265.77013975, 114779.79406061, 315688.86238959, 100864.03466346,
       144798.98470417, 132503.35130581, 153615.15489985, 129308.80350956,
       151561.29339103, 352848.06294281, 105376.62684428, 129722.64710973,
       198206.74624368, 200859.59452427, 225564.48393273, 122261.683014  ,
       159752.30070967, 137637.90928148, 186671.29267326, 462858.40015043,
       143304.46393598, 118291.25923982, 120113.86295687, 101640.66384115,
       223162.0476431 , 106053.7805212 , 223186.97317092, 239252.55127812,
       227865.4455389 , 113907.76383082, 235914.42262947, 126520.59518688,
       167461.79392589, 365235.79474299, 143092.87254323, 138074.01355528,
       498970.97949689, 146287.52518515, 284734.53368373, 176466.81694059,
       369209.79856821, 160448.41983188, 175090.66926303, 116879.66434148,
       172922.15579122, 208998.98813822, 152660.93745575, 168358.46734185,
       111299.21341153, 285855.23295458, 130171.70355352, 125333.85426186,
       192018.97699658,  98677.73845768, 119567.75169834, 191494.83945765,
       229303.54091911, 146677.40326854, 161744.61860735, 367565.90887743,
       147769.6059469 , 119653.19903426, 100583.61346854, 187485.05682115,
       142105.09901602, 409278.38578199, 179687.85793946, 114541.17678145,
       125795.09837649, 285478.06196686, 269166.78612185,  19660.99983897,
       229546.89368166, 215742.79887699, 115946.69522047, 117970.24535898,
        98777.94274423,  97710.81862452, 133359.40748819, 161773.03065907,
        85320.77707149, 182882.56205631, 143802.89199939, 381806.16894   ,
       163024.90164904, 198167.65240703, 129804.08286193,  65324.14605013,
       285027.17220702, 173027.28747951, 298678.26189195, 126867.23364587,
       139819.47891259, 226158.21226501, 200849.33216967, 111016.85080121])